# An Overview of NumPy Arrays

**NumPy** provides numerical back end for nearly every scientific or technical library for Python.It is an important part of the *Scientific Python Ecosystem*. It is an acronym for "Numerical Python".

More information about NumPy is available at [numpy website](http://www.numpy.org).

## Advantages of NumPy

*    NumPy is extremely fast compared to core Python.
*    Many advanced Python libraries such as *SciPy*, *Scikit-Learn* and *Keras* make extensive use of NumPy libraries.
*    NumPy comes with variety of built-in functionalities which in case of core Python, one has to bulit custom code.

## Importing NumPy

In order to use NumPy library, we have to import it in our program. By convention, **numpy module** is imported under the alias **np**

```python
import numpy as np
```
After this we can access functions and classes in the numpy module using np namespace.

## NumPy Array Objects

NumPy's main object is the *homogenous multidimensional array*. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.
	
For example, the coordinates of a point in 3D space $[1, 2, 1]$ has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

![A two-dimensional array](Figure\NumpyFig01.png)

NumPy’s array class is called `ndarray`. The more important attributes of an ndarray object are:

|Attributes|Description|
|:---|:---|
|`ndim`|Number of dimensions (axes) of the array|
|`shape`|Number of elements for each dimension of the array. For a matrix with n rows and m columns, shape will be (n,m)|
|`size`|Total number of elements in an array. This is equal to the product of the elements of shape|
|`dtype`|The data type of the elements in the array|
|`nbytes`|Number bytes used to store data|

Let us try to understand the attributes with the following examples.

In [1]:
data = np.array([[1, 2], [3, 4], [5, 6] ])
type(data)

NameError: name 'np' is not defined

In [8]:
data.ndim

2

In [9]:
data.shape

(3, 2)

In [10]:
data.size

6

In [11]:
data.dtype

dtype('int32')

In [12]:
data.nbytes

24

##  Data Types

 NumPy arrays consist of homogenous data type. The basic data types supported in NumPy are shown below.

|**dtype**|**Variants**|**Description**
|:---|:---|:---
|`int`|`int8`, `int16`, `int32`, `int64`|Integer
|`uint`|`uint8`, `uint16`, `uint32`, `uint64`|Unsigned (non-negative) integers
|`bool`| `bool`|Boolean (True or false)
`float`|`float8`, `float16`, `float32`, `float64`|Floating-point nmbers
|`complex`|`complex64`, `complex128`, `complex256`| complex-valued floating-point number

In [13]:
data = np.array([1, 2, 3, 4], dtype=int)
data

array([1, 2, 3, 4])

In [14]:
data = np.array([1, 2, 3, 4], dtype=float)
data

array([1., 2., 3., 4.])

In [15]:
data = np.array([1, 2, 3, 4], dtype=complex)
data

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

Once a NumPy array is created its `dtype` cannot be changed, other than creating a new copy with type-casted array value.

In [35]:
data = np.array([1, 2, 3 ], dtype=float)

In [36]:
data

array([1., 2., 3.])

In [37]:
data.dtype

dtype('float64')

In [38]:
data = np.array(data, dtype=int)

In [39]:
data.dtype

dtype('int32')

In [40]:
data

array([1, 2, 3])

we can do it by `astype` attribute of the `ndarray` class

In [22]:
data = np.array([1, 2, 3 ], dtype=float)

In [23]:
data

array([1., 2., 3.])

In [24]:
data.dtype

dtype('float64')

In [25]:
data.astype(int)

array([1, 2, 3])

When computing with NumPy arrays, the data type might get promoted from one type to another, if required by the operation. For example, adding float-valued and complex-valued arrays, the resulting array is a complex-valued array:

In [41]:
d1 = np.array([1, 2, 3 ], dtype=float)
d2 = np.array([1, 2, 3 ], dtype=complex)
d = d1 + d2
d

array([2.+0.j, 4.+0.j, 6.+0.j])

In [42]:
d.dtype

dtype('complex128')

Depending on the application and its requirement, sometime it is essential to create arrays with appropriate data type, for example, `int` or `complex`. The default datatype is float.

In [54]:
np.sqrt(np.array([-1, 0, 1]))

c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [55]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

## Real and Imaginary Parts

Regardless of the value of the `dtype` attribute, all NumPy array instances have the attributes `real` and `imag` for extracting the real and imaginary parts of the array, respectively:

In [30]:
data = np.array([1, 2, 3], dtype=complex)
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [31]:
data.real

array([1., 2., 3.])

In [32]:
data.imag

array([0., 0., 0.])

## Creating Arrays

The functions from the NumPy library that can be used to create arrays of different types:

|Function name|Type of Array|
|:---|:---|
|`np.array`|creates an array from Python list|
|`np.zeros`|Creates an array - with the specified dimension and data type - filled with zeros|
|`np.ones`|Creates an array - with the specified dimension and data type - filled with ones|
|`np.diag`|Creates a diagonal array with specified values along the diagonal and zeros elsewhere|
|`np.arange`|Creates an evenly spaced values between specified start, end and incremental values|
|`np.linspace`|Creates an evenly spaced values between specified start, end, using specified number of elements|
|`np.meshgrid`| Generate coordinate matrices from one dimensional  coordinate vectors|
|`np.random.rand`|Generates an array with random numbers that are uniformly distributed between 0 and 1|

**`np.array`** 
creates an array from a python list

In [56]:
data = np.array([1, 2, 3, 4 ])
data.shape

(4,)

In [57]:
data = np.array([1, 2, 3, 4])
data, data.ndim, data.shape

(array([1, 2, 3, 4]), 1, (4,))

To create a two-dimensional array with the same data as in the previous example, we can use a nested Python list:

In [58]:
data = np.array([[1, 2 ], [3 ,4 ] ] )
data.shape

(2, 2)

In [59]:
data = np.array([[1, 2 ], [3, 4 ] ])
data, data.ndim, data.shape

(array([[1, 2],
        [3, 4]]),
 2,
 (2, 2))

### Arrays filled with constant values

**`np.zeros`** and **`np.ones`** <br>
Creat an array - with the specified dimension and data type - filled with zeros and ones respectively.

In [60]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [61]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
a = np.ones([2, 3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

`np.zeros` and `np.ones` functions also accept an optional keyword argument that specifies the data type for the elements in the array. By default, the data type is float64, and it can be changed to the required type by explicitly specify the dtype argument.

In [63]:
data = np.ones(4)
data, data.dtype

(array([1., 1., 1., 1.]), dtype('float64'))

In [64]:
data = np.ones(4, dtype=int)
data, data.dtype

(array([1, 1, 1, 1]), dtype('int32'))

An array filled with an arbitrary constant value can be generated by first creating an array filled with
ones, and then multiply the array with the desired fill value.<br>
However, NumPy also provides the function `np.full` that does exactly this in one step.

In [65]:
5.4*np.ones(4)

array([5.4, 5.4, 5.4, 5.4])

In [66]:
x1 = 5.4*np.ones(4)
x2 = np.full(4, 5.4)
x1, x2

(array([5.4, 5.4, 5.4, 5.4]), array([5.4, 5.4, 5.4, 5.4]))

An already created array can also be filled with constant values using the np.fill function, which takes an array and a value as arguments, and set all elements in the array to the given value. 

In [67]:
np.empty(5)

array([2.12199579e-314, 0.00000000e+000, 2.25293935e-321, 3.79442416e-321,
       0.00000000e+000])

In [68]:
x1 = np.empty(5)
x1.fill(3.0)
x1

array([3., 3., 3., 3., 3.])

In [69]:
x2 = np.full(5, 3.0)
x2

array([3., 3., 3., 3., 3.])

### Arrays filled with Incremental Sequences

`np.arange` Creates an evenly spaced values between specified **start**, **end** and **incremental values**.
```python
np.arange(start, stop, incremental value)
```

In [70]:
np.arange(1, 10, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

`np.linspace` Creates an evenly spaced values between specified start, end, using specified number of elements.
```python
np.linspace(start, stop, number of elemnts)
```

In [71]:
np.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

### Arrays Filled with Logarithmic Sequences

The function `np.logspace` is similar to `np.linspace`, but the increments between the elements in the array are logarithmically distributed, and the first two arguments are the powers of the optional base keyword argument (which defaults to 10) for the start and end values. 

In [72]:
 np.logspace(0, 2, 5) # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

### Mesh-grid Arrays

Multidimensional coordinate grids can be generated using the function `np.meshgrid`. Given two one-dimensional coordinate arrays (that is, arrays containing a set of coordinates along a given dimension), we can generate two-dimensional coordinate arrays using the `np.meshgrid` function. 

In [73]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)

In [74]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [75]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

To evaluate $(x+y)^2$ at all combinations of values from the $x$ and $y$ arrays above, we can use two-dimensional coordinate arrays X and Y.

In [76]:
Z = (X + Y)^2
Z

array([[-1, -4, -3],
       [-3,  2,  3],
       [ 3,  0,  1]], dtype=int32)

### Creating Uninitialized Arrays

To create an array of specific size and data type, but without initializing the elements in the array to any particular values, we can use the function `np.empty`.

In [77]:
np.empty(3, dtype=float)

array([2.12199579e-314, 2.25293935e-321, 3.79442416e-321])

### Creating Arrays with Properties of Other Arrays

It is often necessary to create new arrays that share properties, such as shape and data type, with another
array. NumPy provides a family of functions for this purpose: `np.ones_like`, `np.zeros_like`, `np.full_like`,
and `np.empty_like`. A typical use-case is a function that takes arrays of unspecified type and size as
arguments, and requires working arrays of the same size and type.

In [78]:
x = np.array([[ 1, 2, 3], [4, 5, 6 ], [7, 8, 9 ] ])
y = np.zeros_like(x)
z = np.ones_like(x)

In [79]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [81]:
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

**`np.random.rand()`** Generates an array with random numbers that are uniformly distributed between 0 and 1.

In [82]:
np.random.rand(3, 3)

array([[0.75134541, 0.17858929, 0.04805528],
       [0.39626057, 0.58582192, 0.5479338 ],
       [0.87490819, 0.61910679, 0.84066734]])

### Creating Matrix Arrays

Matrices, or two-dimensional arrays, are an important case for numerical computing. NumPy provides functions for generating commonly used matrices. In particular, the function `np.identity` generates a square matrix with ones on the diagonal and zeros elsewhere:

In [83]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

The similar function `numpy.eye` generates matrices with ones on a diagonal

In [84]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [85]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

To construct a matrix with an arbitrary one-dimensional array on the diagonal we can use the `np.diag` function 

In [86]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## Indexing and Slicing

|Expression|Description 
|:---|:---
|`a[m]`|Select element at index m, where m is an integer (start counting form 0).
|`a[-m]`|Select the mth element from the end of the list, where m is an integer. The last element in the list is addressed as -1, the second-to-last element as -2, and so on.
|`a[m:n]` | Select elements with index starting at m and ending at n -1 (m and n are integers).
|`a[:]` or `a[:-1]`| Select all elements in the given axis
|`a[:n]`| Select elements starting with index 0 and going up to index n -1 (integer).
|`a[m:]` or `a[m:-1]` |Select elements starting with index m (integer) and going up to the last element in the array.
|`a[m:n:p]`| Select elements with index m through n (exclusive), with increment p.
|`a[::-1]`| Select all the elements, in reverse order.

One Dimensional Array

In [66]:
a = np.arange(0, 10, 1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

To select specific elements from this array, for
example the first, the last, and the 5th element we can use integer indexing:

In [67]:
a[0]   # the first element

0

In [68]:
a[-1]  # the last element

9

In [69]:
a[4]   ## fifth element or element at index 4

4

To select a range of elements, say from the *second* to the *second-to-last element*, *selecting every element* and *every second element*, respectively, we can use index slices:

In [70]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [71]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a[1:-1:2]

array([1, 3, 5, 7])

To select the *first five* and the *last five elements* from an array, we can use the slices :5 and -5:, since if m or n is omitted in m:n, the defaults are the beginning and the end of the array, respectively

In [73]:
a[:5]

array([0, 1, 2, 3, 4])

In [74]:
a[-5:]

array([5, 6, 7, 8, 9])

To reverse the array and select only every second value, we can use the slice ::-2

In [75]:
a[::-2]

array([9, 7, 5, 3, 1])

### Multidimensionally Arrays

With multidimensional arrays, element selections like those introduced in the previous section can be applied on each axis (dimension). The result is a reduced array where each element matches the given selection rules. 

In [76]:
f = lambda m, n: n+ 10*m
A = np.fromfunction(f, (6,6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

We can extract columns and rows from this two-dimensional array using a combination of slice and integer indexing:

In [77]:
A[:,1]   # Second Column

array([ 1, 11, 21, 31, 41, 51])

In [78]:
A[1,:]   # Second Row

array([10, 11, 12, 13, 14, 15])

By applying a slice on each of the array axes, we can extract subarrays. 

In [79]:
A[:3,:3]   #  upper half diagonal block matrix

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [80]:
A[3:,3:]       #lower left off-diagonal block matrix

array([[33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])

With element spacing other that 1, submatrices made up from nonconsecutive elements can be extracted:

In [81]:
A[::2, ::2]     #  every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [82]:
 A[1::2, 1::3] # every second and third element starting from 1, 1

array([[11, 14],
       [31, 34],
       [51, 54]])

## NumPy functions for manupulating size and shape of arrays

|Function/Method|Description
|:---|:---
|`np.reshape`| Reshape an N-dimensional array. The total number of elements must remain the same.
|`np.ndarray.flatten`| Create a copy of an N-dimensional array and reinterpret it as a onedimensional array (that is, all dimensions are collapsed into one).
|`np.transpose`| Transpose the array. The transpose operation corresponds to reversing the axes of the array.
|`np.hstack`| Stack a list of arrays horizontally (along axis 1): For example, given a list of column vectors, append the columns to form a matrix.
|`np.vstack`| Stack a list of arrays vertically (along axis 0): For example, given a list of row vectors, append the rows to form a matrix.
|`np.concatenate`| Create a new array by appending arrays after each other, along a given axis.
|`np.append`| Append an element to an array. Creates a new copy of the array.

`np.reshape` Reshape an N-dimensional array. The total number of elements must remain the same.

In [83]:
data = np.array([[1, 2], [3, 4] ])
data

array([[1, 2],
       [3, 4]])

In [84]:
data.shape

(2, 2)

In [85]:
data.reshape(1, 4)

array([[1, 2, 3, 4]])

In [86]:
data.reshape(4)

array([1, 2, 3, 4])

`np.ndarray.flatten` Create a copy of an N-dimensional array and reinterpret it as a one dimensional array (that is, all dimensions are collapsed into one).

In [87]:
data = np.array([[1, 2], [3, 4] ])
data

array([[1, 2],
       [3, 4]])

In [88]:
data.flatten()

array([1, 2, 3, 4])

In [89]:
data.flatten().shape

(4,)

To create two-dimensional array with the same data, we can use a nested Python list:

In [90]:
data.ndim

2

In [91]:
data.shape

(2, 2)

`np.transpose` Transpose the array. The transpose operation corresponds to reversing the axes of the array.

In [92]:
data = np.arange(9)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
data = data.reshape([3,3])
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

`np.hstack` Stack a list of arrays horizontally (along axis 1): For example, given a list of column vectors, append the columns to form a matrix.

In [99]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [100]:
data = data.reshape(5,1)
data

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [101]:
data = np.hstack([data, data, data, data])
data

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

`np.vstack` Stack a list of arrays vertically (along axis 0): For example, given a list of row vectors, append the rows to form a matrix.

In [102]:
data = np.arange(1, 5)
data

array([1, 2, 3, 4])

In [103]:
np.vstack([data, data, data])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

`np.concatenate` Create a new array by appending arrays after each other, along a given axis.

In [104]:
a = np.array([[1, 2], [3, 4] ])
b = np.array([[5, 6]])

In [105]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [106]:
np.concatenate((a, b.T,), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

`np.append` Append an element to an array. Creates a new copy of the array.

In [107]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [108]:
np.append(a, 5)

array([0, 1, 2, 3, 4, 5])

## Vectorized Expressions

*   The purpose of storing numerical data in arrays is to carry out batch operation  that are applied to all elements in the arrays.
*   Efficient use of vectorized expressions eliminates the need of many explicit `for` loops. 

### Broadcasting

 A $3\times3$ matrix is added to a $1\times 3$ row vector and a $3\times1$ column vector, respectively, and the in both cases the result is a $3\times3$ matrix.<br>
However, the elements in the two resulting matrices are different, because the way the elements of the row
and column vectors are broadcasted to the shape of the larger array is different depending on the shape of
the arrays, according to NumPy’s broadcasting rule.

### Arithmetic Operations
*   The standard arithmetic operations with NumPy arrays perform elementwise operations. Consider, for example, the addition, subtraction, multiplication and division of equal-sized arrays:
	
*   In operations between scalars and arrays, the scalar value is applied to each element in the array, as one
	could expect:
	
*   If an arithmetic operation is performed on arrays with incompatible size or shape, a ValueError	exception is raised:

Operator for elementwise arithmetic operation on NumPy arrays:

|**Operator**|**Operation**
|:---|:---
|+, +=|Addition
|-, -=|Subtraction
|\*,\* = | Multiplication
|/| /=| Division
|//| //=| Integer Division
|\**, \**=| Exponentiation

#### Element wise array-array operation

The standard arithmetic operations with NumPy arrays perform elementwise operations. Consider, for example, the addition, subtraction, multiplication and division of equal-sized arrays:

In [109]:
x = np.array([[1, 2 ], [3, 4 ] ])
y = np.array([[5, 6 ], [7, 8 ] ])

x + y

array([[ 6,  8],
       [10, 12]])

In [110]:
y - x

array([[4, 4],
       [4, 4]])

In [111]:
x * y

array([[ 5, 12],
       [21, 32]])

In [112]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

#### Scalar-array operation
In operations between scalars and arrays, the scalar value is applied to each element in the array, as one could expect:

In [113]:
x * 2

array([[2, 4],
       [6, 8]])

In [114]:
2 ** x

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [115]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

If an arithmetic operation is performed on arrays with incompatible size or shape, a ValueError	exception is raised:

In [87]:
x = np.array([[1, 2, 3, 4] ])
x.shape

(1, 4)

In [88]:
x = x.reshape(2, 2)
x, x.shape

(array([[1, 2],
        [3, 4]]),
 (2, 2))

In [89]:
y = np.array([1, 2 , 3, 4 ])
y.shape

(4,)

In [90]:
x / y

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

### Elementwise Functions

In addition to arithmetic expressions using operators, NumPy provides vectorized functions for elementwise evaluation of many elementary mathematical functions and operations. Each of these functions takes a single array (of arbitrary dimension) as input and returns a new array of the same shape, where for each element the function has been applied to the corresponding element in the input array. 

|NumPy function|Description
|:---|:---
|`np.cos, np.sin, np.tan`| Trigonometric functions.
|`np.arccos, np.arcsin. np.arctan`| Inverse trigonometric functions.
|`np.arccosh, np.arcsinh, np.arctanh`| Inverse hyperbolic trigonometric functions.
|`np.arccosh, np.arcsinh, np.arctanh`| Hyperbolic trigonometric functions.
|`np.sqrt`| Square root.
|`np.exp`| Exponential.
|`np.log, np.log2, np.log10`| Logarithms of base e, 2, and 10, respectively.

In [120]:
x = np.linspace(-1, 1, 11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [121]:
y = np.sin(np.radians(x))
y

array([-0.01745241, -0.01396218, -0.01047178, -0.00698126, -0.00349065,
        0.        ,  0.00349065,  0.00698126,  0.01047178,  0.01396218,
        0.01745241])

In [122]:
np.round(y, decimals=4)

array([-0.0175, -0.014 , -0.0105, -0.007 , -0.0035,  0.    ,  0.0035,
        0.007 ,  0.0105,  0.014 ,  0.0175])

#### Many of the mathematical operator functions operates on two input arrays and returns one array:

*Summary of NumPy functions for elementwise mathematical operations*

|NumPy Function| Description
|:---|:---
`np.add`, `np.subtract`, `np.multiply`, `np.divide`| Addition, subtraction, multiplication and division of two NumPy arrays.
|`np.power `|Raise first input argument to the power of the second input argument (applied elementwise).
|`np.remainder`|The remainder of division.
|`np.reciprocal`|The reciprocal (inverse) of each element.
`np.real, np.imag, np.conj`|The real part, imaginary part, and the complex conjugate of the elements in the input arrays
|`np.sign, np.abs`|The sign and the absolute value.
|`np.floor, np.ceil, np.rint`|Convert to integer values.
|`np.round`|Round to a given number of decimals

In [123]:
np.add(np.sin(x)**2, np.cos(x)**2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [124]:
np.sin(x)**2 + np.cos(x)**2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Vectorizing a scalar function

In [1]:
import numpy as np

In [2]:
def Heaviside(x):
    if x>1:
        return 1
    else:
        return 0

In [3]:
Heaviside(-1)

0

In [4]:
Heaviside(1.5)

1

In [5]:
x = np.linspace(-5, 5, 11)

In [6]:
Heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

However, unfortunately this function does not work for NumPy array input.<br>
Using `np.vectorize` the scalar heaviside function can be converted into a vectorized function that
works with NumPy arrays as input:

In [7]:
Heaviside = np.vectorize(Heaviside)
Heaviside(x)

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

### Aggregate Functions 
NumPy provides another set of functions for calculating aggregates for NumPy arrays, which take *an array as input* and by default return a *scalar as output*. For example, statistics such as averages, standard deviations, and variances of the values in the input array, and functions for calculating the sum and the product of elements in an array, are all aggregate functions.

*A summary of aggregate functions*:

|NumPy Function|Description
|:---|:---
|`np.mean`|The average of all values in the array.
|`np.std`|Standard Deviation.
|`np.var`| Variance.
|`np.sum`|Sum of all the elements.
|`np.prod`|Product of all elements.
|`np.cumsum`|Cumulative sum of all elements.
|`np.cumprod`|Cumulative product of all elements.
|`np.min, np.max`| The minimum / maximum value in an array.
|`np.argmin, np.argmax`| The index of the minimum / maximum value in an array.
|`np.all`| Return True if all elements in the argument array are nonzero.
|`np.any`| Return True if any of the elements in the argument array is nonzero

In [37]:
a = np.random.rand(1, 50)
np.mean(a), np.std(a), np.var(a)

(0.546807365161143, 0.2776944598724162, 0.07711421304383297)

In [38]:
a = np.arange(1, 10, 1)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.sum(a), np.cumsum(a)

(45, array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32))

In [40]:
np.prod(a), np.cumprod(a)

(362880, array([     1,      2,      6,     24,    120,    720,   5040,  40320,
        362880], dtype=int32))

In [41]:
np.min(a), np.max(a), np.argmin(a), np.argmax(a)

(1, 9, 0, 8)

In [42]:
np.all(a), np.any(a)

(True, True)

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5 ])
a.all(), a.any()

In [3]:
import numpy as np
data = np.array([[1, 2, 3 ], [4, 5, 6 ], [7, 8, 9 ] ])
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
data.sum()

45

In [5]:
data.sum(axis=0)

array([12, 15, 18])

In [6]:
data.sum(axis=1)

array([ 6, 15, 24])

### Operations on Arrays

In addition to elementwise and aggregation functions, some operations act on arrays as a whole, and
produce transformed array of the same size. 

*Summary of NumPy functions for array operations*

|**Function**|**Description**
|:---|:---
|`np.transpose, np.ndarray.transpose, np.ndarray.T`|The transpose (reverse axes) of an array.
|`np.fliplr / np.flipud`| Reverse the elements in each row /column.
|`np.rot90 `|Rotate the elements along the first two axes by 90 degrees.
|`np.sort`,`np.ndarray.sort`|Sort the element of an array along a given specified axis (which default to the last axis of the array). The np.ndarray method sort performs the sorting in place, modifying the input array.

In [ ]:
data = np.arange(9).reshape(3, 3)
data

In [ ]:
np.transpose(data)

In [ ]:
data = np.random.randn(1, 2, 3, 4, 5)
data.shape

In [ ]:
a = np.random.randn(1, 10)
np.sort(a)

### Matrix and Vector Operations

|`NumPy function `|Description
|:---|:---
|`np.dot`| Matrix multiplication (dot product) between two given arrays representing vectors, arrays, or tensors.
|`np.inner`| Standard deviation.
|`np.cross`| The cross product between two arrays that represent vectors.
|`np.tensordot`| Dot product along specified axes of multidimensional arrays.
|`np.outer`| Outer product (tensor product of vectors) between two arrays representing vectors.
|`np.kron`| Kronecker product (tensor product of matrices) between arrays representing matrices and higher-dimensional arrays.
|`np.einsum`| Evaluates Einstein’s summation convention for multidimensional arrays.

In [43]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [44]:
a = a.reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
b = a.reshape(2, 3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
c = np.dot(a, b)
c

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [47]:
a@b

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [91]:
# matrix-vector multiplication

a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
b = np.arange(1, 4)
b

array([1, 2, 3])

In [93]:
np.dot(a, b)

array([14, 32, 50])

In [94]:
a@b

array([14, 32, 50])

In [95]:
type(6.6e-16)

float

In [ ]:
For more detail, one may go through the book of

# Bibliography

```{bibliography}
```